apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
  labels:
    app: comments
spec:
  replicas: 2   # run 2 pods for better availability
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: joshuaombasa/cluester2-test-comments:latest
          ports:
            - containerPort: 4031
          resources:                # resource requests/limits for stability
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:            # health check
            httpGet:
              path: /health
              port: 4031
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:           # ensures traffic only hits ready pods
            httpGet:
              path: /ready
              port: 4031
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: comments-srv
  labels:
    app: comments
spec:
  selector:
    app: comments
  ports:
    - name: http
      protocol: TCP
      port: 4031
      targetPort: 4031
  type: ClusterIP   # internal service (can change to LoadBalancer/NodePort if needed)
