apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: posts
  template:
    metadata:
      labels: 
        app: posts
    spec:
      containers:
        - name: posts
          image: joshuaombasa/cluester2-test-posts


---


apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  selector:
    apps: posts
  ports:
    - name: posts
      protocol: TCP
      port: 3030
      targetPort: 3030
    
         
      