apiVersion: apps/v1
kind: Deployment
metadata: 
  name: query-depl
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: joshuaombasa/cluester2-test-query:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3034

---

apiVersion: v1
kind: Service
metadata:
  name: query-srv
  labels:
    app: query
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 3034
      targetPort: 3034
